# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiaDeFeira' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiaDeFeira
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

 
 
  target 'DiaDeFeiraTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
