name: Dia de Feira 
on:
 pull_request:
 push:
   branches:
     — develop
     — master
     — gitWorkflow
jobs:
 test:
   name: Unit Tests
   runs-on: macOS-latest
   strategy:
       matrix:
         destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
   steps:
     — name: Select Xcode 11.3
       run: sudo xcode-select -s /Applications/Xcode_11.3.app
     — name: Run tests
       run: |
         xcodebuild clean test -project DiaDeFeira.xcodeproj -scheme  DiaDeFeira -destination "${destination}" CODE_SIGN_IDENTITY=”” CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
         bash <(curl -s https://codecov.io/bash)
       env: 
        destination: ${{ matrix.destination }}