name: Dia de Feira 
on: [push]
jobs:
 test:
   name: Unit Tests
   runs-on: macOS-latest
   strategy:
       matrix:
         destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Select Xcode 11.3
       run: sudo xcode-select -s /Applications/Xcode_11.3.app
     - name: Run tests
       run: cd DiaDeFeira
        xcodebuild clean test -project DiaDeFeira.xcodeproj -scheme  DiaDeFeira -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 11' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
       env: 
        destination: ${{ matrix.destination }}